spring: 
  application: 
     name: InstituteService
  datasource: 
    url: jdbc:mysql://ulearn-mysql.cdvo6qjmkkri.ap-south-1.rds.amazonaws.com:3306/ulearn_dev_sadmin
    username: ulearn
    password: ULearn2121
  jpa:
    hibernate: 
      ddl-auto: none
 
server: 
  port: 8089
  servlet: 
    contextPath: /default
name: instute-default-yml
environment: default
enabled: true
contextpath: /default
servers: 
   - www.default.com
   - www.default1.com
logging: 
      file: 
        name: logs/instute_default_logs.log
      pattern:
        console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
        file: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
      level:
        org.springframework.web: ERROR
        org.ulearn.*: INFO
        org.hibernate: ERROR
        
      
jwt.secret.key: secret
jwt.token.validity: 36000000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
        
        
---
spring: 
  profiles: dev
  application: 
     name: InstituteService
  datasource: 
    url: jdbc:mysql://ulearn-mysql.cdvo6qjmkkri.ap-south-1.rds.amazonaws.com:3306/ulearn_dev_sadmin
    username: ulearn
    password: ULearn2121
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate: 
      ddl-auto: none
      use-new-id-generator-mappings: false
server: 
  port: 8087
  servlet: 
    contextPath: /dev
name: institute-dev-yml
environment: dev
enabled: true
contextpath: /dev
servers: 
   - www.dev.com
   - www.dev1.com
logging: 
      file: 
        name: logs/institute_dev_logs.log
      pattern:
        console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
        file: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
      level:
        org.springframework.web: ERROR
        org.ulearn.*: INFO
        org.hibernate: ERROR
        
  
jwt.secret.key: secret
jwt.token.validity: 36000000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka      

        
        
---      
spring: 
  profiles: prod
  application: 
     name: InstituteService
  datasource: 
    url: jdbc:mysql://localhost:3306/ulearn
    username: root
    password: 
  jpa:
    hibernate: 
      ddl-auto: none
      use-new-id-generator-mappings: false
server: 
  port: 8087
  servlet: 
    contextPath: /prod
name: institute-prod-yml
environment: prod
enabled: true
contextpath: /prod
servers: 
   - prod
   - prod.com
logging: 
      file: 
        name: logs/institute_prod_logs.log
      pattern:
        console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
        file: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
      level:
        org.springframework.web: ERROR
        org.ulearn.*: INFO
        org.hibernate: ERROR
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka